INSERT INTO public.category(name) VALUES ('Мелкая бытовая техника');
INSERT INTO public.category(name) VALUES ('Крупная бытовая техника');
INSERT INTO public.category(name) VALUES ('Телевизоры и аксесуары');

INSERT INTO public.manufacturer(title) VALUES ('Gorenje');
INSERT INTO public.manufacturer(title) VALUES ('Beko');
INSERT INTO public.manufacturer(title) VALUES ('Samsung');
INSERT INTO public.manufacturer(title) VALUES ('LG');
INSERT INTO public.manufacturer(title) VALUES ('Siemens');
INSERT INTO public.manufacturer(title) VALUES ('Bosch');
INSERT INTO public.manufacturer(title) VALUES ('Philips');
INSERT INTO public.manufacturer(title) VALUES ('Saturn');
INSERT INTO public.manufacturer(title) VALUES ('SONY');
INSERT INTO public.manufacturer(title) VALUES ('Ozone');
INSERT INTO public.manufacturer(title) VALUES ('Xiaomi');
INSERT INTO public.manufacturer(title) VALUES ('Ergo');
INSERT INTO public.manufacturer(title) VALUES ('Romsat');
INSERT INTO public.manufacturer(title) VALUES ('ProLink');

INSERT INTO public.subcategory(subname, category_id) VALUES ('Стиральные машины', 2);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Холодильники', 2);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Газовые плиты', 2);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Пылесосы', 1);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Электрочайники', 1);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Телевизоры', 3);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Акустика Hi-Fi', 3);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Домашние кинотеатры', 3);
INSERT INTO public.subcategory(subname, category_id) VALUES ('DVD/HD-медиаплееры', 3);
INSERT INTO public.subcategory(subname, category_id) VALUES ('Аксессуары', 3);

INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	 'Отличный холодильник , работает тихо , продукты прекрасно сохраняются . После ручной разморозки не могу нарадоваться режимом NeoFrost( синяя лампа в холодильной камере обеззараживает). Надеюсь , что послужит долго )',	11599,	'RCNK310E20S',	2,	2);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'С нижней морозильной камерой',	15999,	'RB33J3201SA/UA',	3,	2);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	 'Вот и я решил себя порадовать стиралкой, купил модель LG FH0B8ND1 (хотел с прямым приводом, т.к. с другими вариантами я уже пользовался), на следующий день привезли и распаковали. В тот же день сделал 3 стирки в разных режимах. Работает очень тихо, особенно в тежиме стирки, слышно когда бельё плещется в воде, но звуков мотора не слышно. Отжимает качественно как на 800 так и на 1000 оборотов. В лотке для порошка ничего не остаётся, хорошо забирает без остатка. В темноте приборная доска светится как новогодняя ёлка)',	10899,	'FH0B8ND1',	4,	1);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Economy bubble бесполезная функция, так как ни пены особой , ни качество стирки она не улучшает . Еще минус в быстрой стирке 15, при смене температуры на 40 С меняется время стирки на 40 мин., а то и 60 мин. И это огорчает. Вообще , машинка не порадовала меня да и еще за такие деньги.',	11999,	'WW60K42106WDUA',	3,	1);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	 'Плита удобная. Хорошая чугунная решетка, мощные конфорки. В духовке пока испробовала только режимы классический и гриль, обоими довольно. Котлеты в режиме классический получились диетическими и сочными, а рёбрышки в режиме большой гриль - с румяной корочкой',	7899,	'K 5341 WF-B	', 1,	3);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Для мене важливе поєднання функціональності і краси. В цій плиті все є ) Чавунні решітки, газ-контроль духовки, скляна прозора кришка, красивий дизайн. Підкупили також 2 роки гарантії від виробника - навіть газовщиця, яка підключала, здивувалася (на інші ТМ рік). Впродовж 14 днів, поки можна було повернути її назад до магазину, спробувала духовку - дуже важливо було рівномірне запікання. Все ок! Є ще газовий гриль, але поки цю функцію не опробувала. Подобається розташування маленької і великої комфорки попереду, а середні дві однакові подалі. На передній малій зручно робити каву, а на великій смажити щось на пательні, не треба тягнутися. Електроподжиг зручний, легкий. Задоволена поки всім.',	6015,	'FSGT52115GW',	2,	3);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT', 'Для сухой уборки с мешком',	4499,	'VC21F60JUH1/EV',	3,	4);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Користуюся даним виробом більше півроку.Його перевагами є надійність і зручність,але головне це потужність. На половині своєї потужності здатен підняти коврик.Проста і зрозуміла система фільтрації при своєчасному чищенні працює на відмінно. Рекомендую всім.В даній ціньовій категорії я вважаю його найкращим.',	3099,	'BGS1U1800',	6,	4);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'из имевшихся в продаже чайников до 1000 грн. выбрал именно этот. Первое на что обратил внимание - без запаха, у остальных из пластика даже в этой ценовой категории запах пластика был от явного вонючего до чуть заметного. В достоинствах и недостатках укажу первое впечатление, а время покажет насколько будет долговечен. На упаковке производитель заявляет пробег чайника - 7500 кипячений. По обслуживанию при выборе чайника и покупке его замечаний нет. Спасибо за оперативные ответы по существу без воды" в Комфи в МОСТ-сити (Днепр).',	999, 'HD9305/21',	7,	5);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	'Ёмкость, (л)  - 1,7 л',	305, 'ST-EK8437 White/Lt. Green',	8,	5);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT', 'Телевизор в пользовании уже более 2х месяцев.Никаких проблем найдено не было, Smart TV работает на высоте, все фильмы показывает отлично! Качество изображения ( особенно если смотришь в качестве HDR) - глаз не может нарадоваться! Фильм реально оживает! Управление очень легкое - на пульте минимум кнопок+ голосовое управление - очень удобно). Благодаря возможности подключения к Wi-Fi нет никаких проводов, антен и т.д. Не знаю, у кого что тупит - у меня все работает на 100% Советую всем!',	19499,	'UE40MU6100UXUA',	3,	6);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Если источник, который вы хотите подключить к телевизору, поддерживает HDR - картинка будет очень годная. Смарт немного своеобразный, но вполне жизнеспособный. Телевизор очень легкий по весу. Отличный выбор для приставок XboxOneX и PS4Pro',	16999,	'43UJ630V',	4,	6);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	'Суммарная мощность звука Общая мощность звука, которую выдают динамики устройства. 720 Вт',	7599,	'CJ45',	4,	7);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Суммарная мощность звука Общая мощность звука, которую выдают динамики устройства. 70 Вт',	4499,	'MCM2350/12',	7,	7);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Все отлично, звук приятный. Беспроводный саб не подводит и работает четко (выключается вместе с выключением самой панели)',	9909,	'HTCT390',	9,	8);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	'Новый саундбар Samsung HW-MS750 относится к премиальной серии устройств Sound + «все в одном» и предлагает своему владельцу очень насыщенный звук с широкой звуковой сценой. Подключение без проводов, удобное крепление, цельная металлическая конструкция, огромная мощность звука – все это делает новый саундбар Samsung HW-MS750 великолепным выбором.',	19999,	'HW-MS750/RU',	3,	8);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Приставка неплохая, работает достаточно шустро. Больше всего понравилось, что к приставке можно подключить обычную компьютерную мышь, что очень облегчило пользование. Единственный минус, по моему мнению, что приставка очень долго загружается при запуске. Ну а в общем покупкой доволен.',	1555,	'HD T2 Wi-Fi',	10,	9);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	'Отличная приставка. Соответствует заявленным характеристикам. Прекрасный внешний вид, качество сборки. WI Fi работает отлично. Удобный интерфейс. В целом очень довольна. Спасибо за доставку магазину. Рекомендую.',	2149,	'MDZ-16-AB',	11,	9);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	'Тюнер цифрового ТВ ',	499,	'DVB-T2 1108',	12,	10);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('ABSENT',	'Тюнер цифрового ТВ', 	549,	 'T2900HD',	13,	10);
INSERT INTO public.item(availability, description, price, title, manufacturer_id, subcategory_id)	VALUES ('PRESENT',	'Переходник для аудио-видеотехники', 	159,	 'PB008 DVI-D - HDMI A Socket Adaptor',	14,	10);
